/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    brands: Brand;
    'product-categories': ProductCategory;
    products: Product;
    branches: Branch;
    services: Service;
    projects: Project;
    painters: Painter;
    leads: Lead;
    'quotation-requests': QuotationRequest;
    'site-visit-requests': SiteVisitRequest;
    enquiries: Enquiry;
    'design-projects': DesignProject;
    'design-spaces': DesignSpace;
    'design-surfaces': DesignSurface;
    'design-preferences': DesignPreference;
    'design-palettes': DesignPalette;
    'design-variants': DesignVariant;
    'design-product-plan': DesignProductPlan;
    'design-events': DesignEvent;
    complaints: Complaint;
    'ai-sessions': AiSession;
    'ai-lead-summaries': AiLeadSummary;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    painters: PaintersSelect<false> | PaintersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'quotation-requests': QuotationRequestsSelect<false> | QuotationRequestsSelect<true>;
    'site-visit-requests': SiteVisitRequestsSelect<false> | SiteVisitRequestsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'design-projects': DesignProjectsSelect<false> | DesignProjectsSelect<true>;
    'design-spaces': DesignSpacesSelect<false> | DesignSpacesSelect<true>;
    'design-surfaces': DesignSurfacesSelect<false> | DesignSurfacesSelect<true>;
    'design-preferences': DesignPreferencesSelect<false> | DesignPreferencesSelect<true>;
    'design-palettes': DesignPalettesSelect<false> | DesignPalettesSelect<true>;
    'design-variants': DesignVariantsSelect<false> | DesignVariantsSelect<true>;
    'design-product-plan': DesignProductPlanSelect<false> | DesignProductPlanSelect<true>;
    'design-events': DesignEventsSelect<false> | DesignEventsSelect<true>;
    complaints: ComplaintsSelect<false> | ComplaintsSelect<true>;
    'ai-sessions': AiSessionsSelect<false> | AiSessionsSelect<true>;
    'ai-lead-summaries': AiLeadSummariesSelect<false> | AiLeadSummariesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'manager' | 'content_editor' | 'sales' | 'branch_staff' | 'viewer')[];
  /**
   * For branch staff: the outlet this user is responsible for.
   */
  branch?: (number | null) | Branch;
  phone?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from the name if left blank.
   */
  slug?: string | null;
  region?: string | null;
  district?: string | null;
  fullAddress?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Google Maps link / pin.
   */
  mapLink?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  operatingHours?:
    | {
        day?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
        open?: string | null;
        close?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  servicesAvailable?: (number | Service)[] | null;
  active?: boolean | null;
  /**
   * Verification of the information in this record. Unverified content must not be presented to customers as fact.
   */
  verification: {
    status: 'unverified' | 'pending_review' | 'verified';
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
    /**
     * Source / discrepancy notes.
     */
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from the name if left blank.
   */
  slug?: string | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  sectors?: ('residential' | 'commercial')[] | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short intro shown at the top of the service page.
   */
  heroIntro?: string | null;
  scope?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title?: string | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  customerProvides?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  hiltyConfirms?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Warranty / plan claims. Keep UNVERIFIED until officially confirmed.
   */
  warranty?: {
    hasWarranty?: boolean | null;
    planName?: string | null;
    terms?: string | null;
  };
  displayOrder?: number | null;
  active?: boolean | null;
  /**
   * Verification of the information in this record. Unverified content must not be presented to customers as fact.
   */
  verification: {
    status: 'unverified' | 'pending_review' | 'verified';
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
    /**
     * Source / discrepancy notes.
     */
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessible description of the image.
   */
  alt: string;
  /**
   * Source / ownership of this asset. Use only assets owned by or authorised for Hilty.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Private customer documents (BOQs, quotes). Staff-only read.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  label?: string | null;
  kind?: ('boq' | 'quote' | 'design' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from the name if left blank.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  /**
   * Hilty is an authorised retailer/dealer of this brand (not the manufacturer).
   */
  isAuthorisedDealerBrand?: boolean | null;
  website?: string | null;
  notes?: string | null;
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from the name if left blank.
   */
  slug?: string | null;
  /**
   * Canonical category type.
   */
  key:
    | 'interior_paint'
    | 'exterior_paint'
    | 'roof_paint'
    | 'primer_undercoat'
    | 'wood_metal_coatings'
    | 'wall_preparation'
    | 'thinners_solvents'
    | 'brushes_rollers_tools'
    | 'waterproofing_protective';
  description?: string | null;
  image?: (number | null) | Media;
  displayOrder?: number | null;
  active?: boolean | null;
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from the name if left blank.
   */
  slug?: string | null;
  brand?: (number | null) | Brand;
  category: number | ProductCategory;
  useTypes?: ('interior' | 'exterior' | 'roof' | 'wood' | 'metal')[] | null;
  finish?: ('matt' | 'silk' | 'satin' | 'semi_gloss' | 'gloss' | 'textured' | 'other') | null;
  /**
   * Describe colour availability. Do not imply Hilty owns colour names/IP.
   */
  colourAvailability?: string | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  surfaceCompatibility?:
    | {
        surface?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Surface-preparation guidance.
   */
  surfacePreparation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  applicationInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  recommendedPrimer?: string | null;
  recommendedUndercoat?: string | null;
  recommendedTopcoat?: string | null;
  /**
   * Coverage in m² per litre.
   */
  coveragePerLitre?: number | null;
  recommendedCoats?: number | null;
  dryingTime?: {
    touchDry?: string | null;
    recoat?: string | null;
  };
  packSizes?:
    | {
        litres?: number | null;
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Safety notes (handling, ventilation, storage).
   */
  safetyNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Technical data sheet (owned/authorised only).
   */
  tdsFile?: (number | null) | Media;
  /**
   * Authorised link to the manufacturer TDS.
   */
  tdsUrl?: string | null;
  /**
   * Authorised source of the technical information above (e.g. manufacturer TDS name/URL). Shown on the product page for traceability.
   */
  technicalSource?: string | null;
  pricing?: {
    price?: number | null;
    currency?: string | null;
    priceVerified?: boolean | null;
    /**
     * Only enable once the price is verified.
     */
    showPricePublicly?: boolean | null;
  };
  /**
   * Per-branch availability. Default is "Contact branch for availability".
   */
  stock?:
    | {
        branch?: (number | null) | Branch;
        status?: ('in_stock' | 'low' | 'out_of_stock' | 'contact_branch') | null;
        showPublicly?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show in the Featured section (admin selection).
   */
  featured?: boolean | null;
  /**
   * Show in the Popular section (admin selection — not based on activity).
   */
  popular?: boolean | null;
  active?: boolean | null;
  /**
   * Can be included in quotation requests.
   */
  quotationEligible?: boolean | null;
  /**
   * Verification of the information in this record. Unverified content must not be presented to customers as fact.
   */
  verification: {
    status: 'unverified' | 'pending_review' | 'verified';
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
    /**
     * Source / discrepancy notes.
     */
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from the name if left blank.
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  /**
   * e.g. Apartment repaint, Office exterior.
   */
  projectType?: string | null;
  sector?: ('residential' | 'commercial') | null;
  /**
   * Scope of work delivered.
   */
  scope?: string | null;
  servicesUsed?: (number | Service)[] | null;
  productsUsed?: (number | Product)[] | null;
  /**
   * Before image (authorised).
   */
  beforeImage?: (number | null) | Media;
  /**
   * After image (authorised).
   */
  afterImage?: (number | null) | Media;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  completionDate?: string | null;
  client?: {
    name?: string | null;
    testimonial?: string | null;
    /**
     * Record of the consent under which this personal data was collected.
     */
    consent?: {
      given?: boolean | null;
      purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
      channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
      timestamp?: string | null;
      notes?: string | null;
    };
  };
  featured?: boolean | null;
  active?: boolean | null;
  /**
   * Verification of the information in this record. Unverified content must not be presented to customers as fact.
   */
  verification: {
    status: 'unverified' | 'pending_review' | 'verified';
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
    /**
     * Source / discrepancy notes.
     */
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "painters".
 */
export interface Painter {
  id: number;
  fullName: string;
  type?: ('painter' | 'contractor' | 'company') | null;
  phone: string;
  whatsapp?: string | null;
  email?: string | null;
  region?: string | null;
  districts?:
    | {
        district?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        skill?: string | null;
        id?: string | null;
      }[]
    | null;
  yearsExperience?: number | null;
  portfolio?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Sensitive ID reference — staff only.
   */
  idNumber?: string | null;
  status?: ('pending' | 'approved' | 'suspended' | 'rejected') | null;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Verification of the information in this record. Unverified content must not be presented to customers as fact.
   */
  verification: {
    status: 'unverified' | 'pending_review' | 'verified';
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
    /**
     * Source / discrepancy notes.
     */
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone?: string | null;
  email?: string | null;
  source?:
    | ('website_form' | 'whatsapp' | 'ai_advisor' | 'site_visit' | 'quotation' | 'design_studio' | 'import' | 'other')
    | null;
  interest?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'qualified' | 'converted' | 'lost') | null;
  assignedTo?: (number | null) | User;
  branch?: (number | null) | Branch;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotation-requests".
 */
export interface QuotationRequest {
  id: number;
  reference?: string | null;
  customerName: string;
  phone?: string | null;
  email?: string | null;
  projectType?: string | null;
  sector?: ('residential' | 'commercial') | null;
  description?: string | null;
  interiorExterior?: ('interior' | 'exterior') | null;
  /**
   * Approximate area in square metres (m²).
   */
  area?: number | null;
  /**
   * Optional budget range provided by the customer.
   */
  budget?: string | null;
  /**
   * Complete deterministic paint-calculator result saved with this request (estimate — requires site verification).
   */
  calculation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  surfaces?:
    | {
        surface?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uploaded BOQ / project documents (stored privately).
   */
  boqFiles?:
    | {
        file?: (number | null) | Document;
        id?: string | null;
      }[]
    | null;
  productsInterested?: (number | Product)[] | null;
  preferredBranch?: (number | null) | Branch;
  status?: ('received' | 'in_review' | 'quoted' | 'accepted' | 'declined' | 'expired') | null;
  quotedAmount?: number | null;
  quoteFile?: (number | null) | Document;
  assignedTo?: (number | null) | User;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-visit-requests".
 */
export interface SiteVisitRequest {
  id: number;
  reference?: string | null;
  name: string;
  phone?: string | null;
  email?: string | null;
  location?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  preferredDate?: string | null;
  preferredTime?: string | null;
  propertyType?: string | null;
  notes?: string | null;
  branch?: (number | null) | Branch;
  assignedTo?: (number | null) | User;
  status?: ('requested' | 'scheduled' | 'completed' | 'cancelled') | null;
  scheduledFor?: string | null;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  reference?: string | null;
  type: 'contractor_account' | 'developer' | 'project_pricing' | 'bulk_supply' | 'general';
  /**
   * Contact person.
   */
  name: string;
  company?: string | null;
  role?: string | null;
  phone: string;
  email?: string | null;
  /**
   * Company registration / TIN (optional).
   */
  registrationNumber?: string | null;
  projectDescription?: string | null;
  /**
   * Approximate area in m² (optional).
   */
  estimatedArea?: number | null;
  productsInterested?: (number | Product)[] | null;
  /**
   * Products / quantities for bulk supply.
   */
  quantities?: string | null;
  /**
   * Uploaded BOQ / project documents (stored privately).
   */
  documents?:
    | {
        file?: (number | null) | Document;
        id?: string | null;
      }[]
    | null;
  preferredBranch?: (number | null) | Branch;
  status?: ('new' | 'contacted' | 'qualified' | 'converted' | 'closed') | null;
  assignedTo?: (number | null) | User;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-projects".
 */
export interface DesignProject {
  id: number;
  reference?: string | null;
  /**
   * Customer/user identifier where applicable (session or account id).
   */
  customerRef?: string | null;
  /**
   * Project name.
   */
  name: string;
  sector?: ('residential' | 'commercial') | null;
  location?: string | null;
  branch?: (number | null) | Branch;
  status?:
    | (
        | 'draft'
        | 'surfaces_confirmed'
        | 'palette_selected'
        | 'visualised'
        | 'mapped'
        | 'measured'
        | 'saved'
        | 'converted'
        | 'archived'
      )
    | null;
  language?: ('en' | 'sw') | null;
  quotationStatus?: ('none' | 'requested' | 'quoted' | 'accepted' | 'declined') | null;
  linkedQuotation?: (number | null) | QuotationRequest;
  linkedSiteVisit?: (number | null) | SiteVisitRequest;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-spaces".
 */
export interface DesignSpace {
  id: number;
  project: number | DesignProject;
  name: string;
  /**
   * Room / surface type, e.g. living_room, exterior_facade, roof.
   */
  surfaceType?: string | null;
  interiorExterior?: ('interior' | 'exterior') | null;
  /**
   * Original upload — stored PRIVATELY (retained for comparison).
   */
  originalImage?: (number | null) | Document;
  /**
   * Safely re-encoded image (EXIF/location stripped).
   */
  processedImage?: (number | null) | Document;
  imageWidth?: number | null;
  imageHeight?: number | null;
  /**
   * Optional actual measurements (metres).
   */
  measurements?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  surfaceCondition?: ('good' | 'fair' | 'poor') | null;
  /**
   * Lighting description (e.g. bright daylight, warm indoor).
   */
  lighting?: string | null;
  /**
   * Customer confirmed they own / may use this image.
   */
  ownershipConfirmed?: boolean | null;
  privacyStatus?: ('private' | 'deleted') | null;
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-surfaces".
 */
export interface DesignSurface {
  id: number;
  space: number | DesignSpace;
  type: 'wall' | 'ceiling' | 'roof' | 'gate' | 'wood' | 'metal' | 'other';
  /**
   * Editable mask data (polygons / RLE). Versioned.
   */
  mask?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional raster mask (private).
   */
  maskImage?: (number | null) | Document;
  maskVersion?: number | null;
  /**
   * No rendering until the user confirms the intended surface.
   */
  confirmedByUser?: boolean | null;
  /**
   * Surface area where manually supplied (m²).
   */
  areaM2?: number | null;
  conditionNotes?: string | null;
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-preferences".
 */
export interface DesignPreference {
  id: number;
  project: number | DesignProject;
  /**
   * e.g. modern, classic, minimal.
   */
  preferredStyle?: string | null;
  mood?: string | null;
  temperature?: ('warm' | 'cool' | 'neutral') | null;
  desiredColours?:
    | {
        colour?: string | null;
        id?: string | null;
      }[]
    | null;
  avoidColours?:
    | {
        colour?: string | null;
        id?: string | null;
      }[]
    | null;
  furnitureColours?:
    | {
        colour?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. matt, satin, silk, gloss.
   */
  preferredFinish?: string | null;
  /**
   * Durability / cleanability requirement.
   */
  durability?: string | null;
  budgetRange?: string | null;
  /**
   * High-traffic / lifestyle factors.
   */
  factors?: {
    children?: boolean | null;
    pets?: boolean | null;
    highTraffic?: boolean | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-palettes".
 */
export interface DesignPalette {
  id: number;
  project?: (number | null) | DesignProject;
  name: string;
  /**
   * e.g. main wall, accent, trim, ceiling.
   */
  roles?:
    | {
        role?: string | null;
        /**
         * Shade label (approximate on screen).
         */
        shadeName?: string | null;
        /**
         * Approximate hex — NOT an exact colour promise.
         */
        hexApprox?: string | null;
        /**
         * Verified product this shade maps to.
         */
        product?: (number | null) | Product;
        finish?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Model confidence 0–1 (informational).
   */
  confidence?: number | null;
  status?: ('proposed' | 'selected' | 'rejected') | null;
  /**
   * Why this palette was suggested (customer-facing rationale).
   */
  aiExplanation?: string | null;
  /**
   * Verification of the information in this record. Unverified content must not be presented to customers as fact.
   */
  verification: {
    status: 'unverified' | 'pending_review' | 'verified';
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
    /**
     * Source / discrepancy notes.
     */
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-variants".
 */
export interface DesignVariant {
  id: number;
  space: number | DesignSpace;
  palette?: (number | null) | DesignPalette;
  /**
   * Generated image (watermarked "AI visualisation"; stored privately).
   */
  image?: (number | null) | Document;
  provider?: ('openai' | 'gemini') | null;
  /**
   * Configured image model used (not hard-coded).
   */
  model?: string | null;
  status?: ('pending' | 'generating' | 'succeeded' | 'failed') | null;
  promptVersion?: string | null;
  selection?: ('none' | 'selected' | 'rejected') | null;
  /**
   * Customer accepted the "indicative visualisation" disclaimer.
   */
  disclaimerAccepted?: boolean | null;
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-product-plan".
 */
export interface DesignProductPlan {
  id: number;
  project: number | DesignProject;
  surface?: (number | null) | DesignSurface;
  /**
   * Selected shade (approximate on screen).
   */
  shade?: string | null;
  product?: (number | null) | Product;
  primer?: (number | null) | Product;
  topcoat?: (number | null) | Product;
  finish?: string | null;
  /**
   * Verified coverage (m²/L) copied from the product at plan time.
   */
  verifiedCoverage?: number | null;
  coats?: number | null;
  /**
   * Reference of the deterministic calculation used.
   */
  calculatorReference?: string | null;
  /**
   * Quotation reference once converted.
   */
  quotationReference?: string | null;
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-events".
 */
export interface DesignEvent {
  id: number;
  type:
    | 'studio_visit'
    | 'project_started'
    | 'image_uploaded'
    | 'palette_created'
    | 'visual_generated'
    | 'favourite_saved'
    | 'calculation_completed'
    | 'quotation_requested'
    | 'site_visit_requested'
    | 'whatsapp_handoff'
    | 'lead_won'
    | 'lead_lost'
    | 'revenue_recorded'
    | 'followup_scheduled';
  project?: (number | null) | DesignProject;
  branch?: (number | null) | Branch;
  leadRef?: string | null;
  /**
   * Attributable revenue where later recorded.
   */
  value?: number | null;
  currency?: string | null;
  /**
   * Non-PII metadata only (counts / flags). Never images or chat.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints".
 */
export interface Complaint {
  id: number;
  reference?: string | null;
  type?: ('complaint' | 'product_batch_report' | 'warranty_claim') | null;
  customerName: string;
  phone?: string | null;
  email?: string | null;
  branch?: (number | null) | Branch;
  product?: (number | null) | Product;
  batchNumber?: string | null;
  purchaseDate?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  severity?: ('low' | 'medium' | 'high') | null;
  status?: ('open' | 'investigating' | 'resolved' | 'closed') | null;
  resolutionNotes?: string | null;
  assignedTo?: (number | null) | User;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-sessions".
 */
export interface AiSession {
  id: number;
  sessionId: string;
  channel?: ('web' | 'whatsapp') | null;
  locale?: ('en' | 'sw') | null;
  startedAt?: string | null;
  endedAt?: string | null;
  messages?:
    | {
        role?: ('user' | 'assistant' | 'system') | null;
        content?: string | null;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedLead?: (number | null) | Lead;
  /**
   * Record of the consent under which this personal data was collected.
   */
  consent?: {
    given?: boolean | null;
    purpose?: ('service_request' | 'marketing' | 'registration' | 'support') | null;
    channel?: ('website' | 'whatsapp' | 'ai_advisor' | 'in_person' | 'phone' | 'import') | null;
    timestamp?: string | null;
    notes?: string | null;
  };
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-lead-summaries".
 */
export interface AiLeadSummary {
  id: number;
  session?: (number | null) | AiSession;
  summary?: string | null;
  detectedIntent?: string | null;
  recommendedProducts?: (number | Product)[] | null;
  /**
   * Suggested paint system (guidance only — no exact-colour promises).
   */
  recommendedSystem?: string | null;
  customerContact?: {
    name?: string | null;
    phone?: string | null;
    consentGiven?: boolean | null;
  };
  /**
   * 0–1 confidence score.
   */
  confidence?: number | null;
  reviewedBy?: (number | null) | User;
  status?: ('new' | 'reviewed' | 'converted' | 'dismissed') | null;
  /**
   * Data-retention controls. Records past their retain-until date should be reviewed for deletion.
   */
  retention?: {
    retainUntil?: string | null;
    legalBasis?: ('consent' | 'contract' | 'legitimate_interest' | 'legal_obligation') | null;
    notes?: string | null;
  };
  /**
   * Set automatically to the staff member who created this record.
   */
  createdBy?: (number | null) | User;
  /**
   * Set automatically to the staff member who last updated this record.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'painters';
        value: number | Painter;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'quotation-requests';
        value: number | QuotationRequest;
      } | null)
    | ({
        relationTo: 'site-visit-requests';
        value: number | SiteVisitRequest;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'design-projects';
        value: number | DesignProject;
      } | null)
    | ({
        relationTo: 'design-spaces';
        value: number | DesignSpace;
      } | null)
    | ({
        relationTo: 'design-surfaces';
        value: number | DesignSurface;
      } | null)
    | ({
        relationTo: 'design-preferences';
        value: number | DesignPreference;
      } | null)
    | ({
        relationTo: 'design-palettes';
        value: number | DesignPalette;
      } | null)
    | ({
        relationTo: 'design-variants';
        value: number | DesignVariant;
      } | null)
    | ({
        relationTo: 'design-product-plan';
        value: number | DesignProductPlan;
      } | null)
    | ({
        relationTo: 'design-events';
        value: number | DesignEvent;
      } | null)
    | ({
        relationTo: 'complaints';
        value: number | Complaint;
      } | null)
    | ({
        relationTo: 'ai-sessions';
        value: number | AiSession;
      } | null)
    | ({
        relationTo: 'ai-lead-summaries';
        value: number | AiLeadSummary;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  branch?: T;
  phone?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  isAuthorisedDealerBrand?: T;
  website?: T;
  notes?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  key?: T;
  description?: T;
  image?: T;
  displayOrder?: T;
  active?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  category?: T;
  useTypes?: T;
  finish?: T;
  colourAvailability?: T;
  image?: T;
  description?: T;
  surfaceCompatibility?:
    | T
    | {
        surface?: T;
        id?: T;
      };
  surfacePreparation?: T;
  applicationInstructions?: T;
  recommendedPrimer?: T;
  recommendedUndercoat?: T;
  recommendedTopcoat?: T;
  coveragePerLitre?: T;
  recommendedCoats?: T;
  dryingTime?:
    | T
    | {
        touchDry?: T;
        recoat?: T;
      };
  packSizes?:
    | T
    | {
        litres?: T;
        sku?: T;
        id?: T;
      };
  safetyNotes?: T;
  tdsFile?: T;
  tdsUrl?: T;
  technicalSource?: T;
  pricing?:
    | T
    | {
        price?: T;
        currency?: T;
        priceVerified?: T;
        showPricePublicly?: T;
      };
  stock?:
    | T
    | {
        branch?: T;
        status?: T;
        showPublicly?: T;
        id?: T;
      };
  featured?: T;
  popular?: T;
  active?: T;
  quotationEligible?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedAt?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  district?: T;
  fullAddress?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  mapLink?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  operatingHours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        closed?: T;
        id?: T;
      };
  servicesAvailable?: T;
  active?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedAt?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  sectors?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  heroIntro?: T;
  scope?:
    | T
    | {
        item?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  customerProvides?:
    | T
    | {
        item?: T;
        id?: T;
      };
  hiltyConfirms?:
    | T
    | {
        item?: T;
        id?: T;
      };
  warranty?:
    | T
    | {
        hasWarranty?: T;
        planName?: T;
        terms?: T;
      };
  displayOrder?: T;
  active?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedAt?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  location?: T;
  projectType?: T;
  sector?: T;
  scope?: T;
  servicesUsed?: T;
  productsUsed?: T;
  beforeImage?: T;
  afterImage?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  completionDate?: T;
  client?:
    | T
    | {
        name?: T;
        testimonial?: T;
        consent?:
          | T
          | {
              given?: T;
              purpose?: T;
              channel?: T;
              timestamp?: T;
              notes?: T;
            };
      };
  featured?: T;
  active?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedAt?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "painters_select".
 */
export interface PaintersSelect<T extends boolean = true> {
  fullName?: T;
  type?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  region?: T;
  districts?:
    | T
    | {
        district?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  yearsExperience?: T;
  portfolio?:
    | T
    | {
        image?: T;
        id?: T;
      };
  idNumber?: T;
  status?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedAt?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  source?: T;
  interest?: T;
  message?: T;
  status?: T;
  assignedTo?: T;
  branch?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotation-requests_select".
 */
export interface QuotationRequestsSelect<T extends boolean = true> {
  reference?: T;
  customerName?: T;
  phone?: T;
  email?: T;
  projectType?: T;
  sector?: T;
  description?: T;
  interiorExterior?: T;
  area?: T;
  budget?: T;
  calculation?: T;
  surfaces?:
    | T
    | {
        surface?: T;
        id?: T;
      };
  boqFiles?:
    | T
    | {
        file?: T;
        id?: T;
      };
  productsInterested?: T;
  preferredBranch?: T;
  status?: T;
  quotedAmount?: T;
  quoteFile?: T;
  assignedTo?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-visit-requests_select".
 */
export interface SiteVisitRequestsSelect<T extends boolean = true> {
  reference?: T;
  name?: T;
  phone?: T;
  email?: T;
  location?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  preferredDate?: T;
  preferredTime?: T;
  propertyType?: T;
  notes?: T;
  branch?: T;
  assignedTo?: T;
  status?: T;
  scheduledFor?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  reference?: T;
  type?: T;
  name?: T;
  company?: T;
  role?: T;
  phone?: T;
  email?: T;
  registrationNumber?: T;
  projectDescription?: T;
  estimatedArea?: T;
  productsInterested?: T;
  quantities?: T;
  documents?:
    | T
    | {
        file?: T;
        id?: T;
      };
  preferredBranch?: T;
  status?: T;
  assignedTo?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-projects_select".
 */
export interface DesignProjectsSelect<T extends boolean = true> {
  reference?: T;
  customerRef?: T;
  name?: T;
  sector?: T;
  location?: T;
  branch?: T;
  status?: T;
  language?: T;
  quotationStatus?: T;
  linkedQuotation?: T;
  linkedSiteVisit?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-spaces_select".
 */
export interface DesignSpacesSelect<T extends boolean = true> {
  project?: T;
  name?: T;
  surfaceType?: T;
  interiorExterior?: T;
  originalImage?: T;
  processedImage?: T;
  imageWidth?: T;
  imageHeight?: T;
  measurements?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  surfaceCondition?: T;
  lighting?: T;
  ownershipConfirmed?: T;
  privacyStatus?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-surfaces_select".
 */
export interface DesignSurfacesSelect<T extends boolean = true> {
  space?: T;
  type?: T;
  mask?: T;
  maskImage?: T;
  maskVersion?: T;
  confirmedByUser?: T;
  areaM2?: T;
  conditionNotes?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-preferences_select".
 */
export interface DesignPreferencesSelect<T extends boolean = true> {
  project?: T;
  preferredStyle?: T;
  mood?: T;
  temperature?: T;
  desiredColours?:
    | T
    | {
        colour?: T;
        id?: T;
      };
  avoidColours?:
    | T
    | {
        colour?: T;
        id?: T;
      };
  furnitureColours?:
    | T
    | {
        colour?: T;
        id?: T;
      };
  preferredFinish?: T;
  durability?: T;
  budgetRange?: T;
  factors?:
    | T
    | {
        children?: T;
        pets?: T;
        highTraffic?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-palettes_select".
 */
export interface DesignPalettesSelect<T extends boolean = true> {
  project?: T;
  name?: T;
  roles?:
    | T
    | {
        role?: T;
        shadeName?: T;
        hexApprox?: T;
        product?: T;
        finish?: T;
        id?: T;
      };
  confidence?: T;
  status?: T;
  aiExplanation?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedAt?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-variants_select".
 */
export interface DesignVariantsSelect<T extends boolean = true> {
  space?: T;
  palette?: T;
  image?: T;
  provider?: T;
  model?: T;
  status?: T;
  promptVersion?: T;
  selection?: T;
  disclaimerAccepted?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-product-plan_select".
 */
export interface DesignProductPlanSelect<T extends boolean = true> {
  project?: T;
  surface?: T;
  shade?: T;
  product?: T;
  primer?: T;
  topcoat?: T;
  finish?: T;
  verifiedCoverage?: T;
  coats?: T;
  calculatorReference?: T;
  quotationReference?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-events_select".
 */
export interface DesignEventsSelect<T extends boolean = true> {
  type?: T;
  project?: T;
  branch?: T;
  leadRef?: T;
  value?: T;
  currency?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints_select".
 */
export interface ComplaintsSelect<T extends boolean = true> {
  reference?: T;
  type?: T;
  customerName?: T;
  phone?: T;
  email?: T;
  branch?: T;
  product?: T;
  batchNumber?: T;
  purchaseDate?: T;
  description?: T;
  severity?: T;
  status?: T;
  resolutionNotes?: T;
  assignedTo?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-sessions_select".
 */
export interface AiSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  channel?: T;
  locale?: T;
  startedAt?: T;
  endedAt?: T;
  messages?:
    | T
    | {
        role?: T;
        content?: T;
        timestamp?: T;
        id?: T;
      };
  linkedLead?: T;
  consent?:
    | T
    | {
        given?: T;
        purpose?: T;
        channel?: T;
        timestamp?: T;
        notes?: T;
      };
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-lead-summaries_select".
 */
export interface AiLeadSummariesSelect<T extends boolean = true> {
  session?: T;
  summary?: T;
  detectedIntent?: T;
  recommendedProducts?: T;
  recommendedSystem?: T;
  customerContact?:
    | T
    | {
        name?: T;
        phone?: T;
        consentGiven?: T;
      };
  confidence?: T;
  reviewedBy?: T;
  status?: T;
  retention?:
    | T
    | {
        retainUntil?: T;
        legalBasis?: T;
        notes?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}